### PR TITLE
Fix: dynamically find target dir

### LINKED ISSUE #7: Unable to download aurora engine for integration tests
Hey,

I tried developing and running integration tests, but I am unable to, because of this line:

https://github.com/aurora-is-near/aurora-contracts-sdk/blob/d02d8b93b25735b4755f899a27755777fb09a650/aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs#L98

```rs
impl Action {
    async fn execute(self, engine_path: &Path) -> anyhow::Result<ActionOutput> {
        match self {
            Self::Download => {
                if !engine_path.exists() {
                    // this line fails
                    let target_dir = engine_path.parent().unwrap().canonicalize()?;
                    let git = Git::in_working_dir(target_dir);
                    git.clone("https://github.com/aurora-is-near/aurora-engine.git")
                        .await?;
                }
                Ok(ActionOutput::Unit)
            }
```

`.parent().unwrap()` fails, because parent doesn't exist in my case. I added aurora-contracts-sdk as a git submodule to my repository and linked the Rust dependency via path.
I think you're also lacking docs on how to incorporate the SDK. Is the git submodules method the preferred approach?

### PR DESCRIPTION
**Pull request by birchmd**
The original hardcoded `../target/aurora-engine` only worked when the integration tests were a sub-crate of a workspace, as opposed to being a top-level crate (then the `target` directory is in `./` instead of `../`). This fixes the issue by dynamically looking for a `target` directory to download the Aurora Engine to.

Fixes #7

### CODE REVIEW

File: aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs [hunk 1]
```diff
@@ -199,6 +200,23 @@ async fn add_wasm_target(engine_path: &Path, toolchain: &str) -> anyhow::Result<
...
+        if let Some(p) = current_base.parent() {
+            current_base = p;
+        } else {
+            return Err(anyhow::Error::msg("Failed to find target directory"));
+        }
+        result = current_base.join(TARGET);
+    }
+    Ok(result)
+}
+
```
Comment (aleksuss) [inline aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs:219]: I would add a unit test for this function like this:
```rust
#[test]
fn test_find_target_dir() {
    let result = find_target_dir().unwrap();
    assert_eq!(result, Path::new("../").canonicalize().unwrap().join(TARGET));
}
```
I suppose in the moment of running this test, the directory `target` should exist.

**Review by aleksuss — APPROVED** [review]
Overall looks good with a couple of nitpicks.

File: aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs [hunk 2]
```diff
@@ -199,6 +200,23 @@ async fn add_wasm_target(engine_path: &Path, toolchain: &str) -> anyhow::Result<
     Ok(())
 }
 
+/// Recursively moves up the path tree, starting with the current directory, to find a `target`
+/// directroy.
```
[the remark this answers is not in the document]
Comment (birchmd) [reply aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs]: Fixed in https://github.com/aurora-is-near/aurora-contracts-sdk/pull/8/commits/3db3859ad0e4f7c3d418a7285f66f4320c2231a9

File: aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs (hunk 1 above)
Comment (birchmd) [reply aurora-rust-sdk/aurora-sdk-integration-tests/src/aurora_engine/repo.rs:219]: Added in https://github.com/aurora-is-near/aurora-contracts-sdk/pull/8/commits/3db3859ad0e4f7c3d418a7285f66f4320c2231a9
